Tighter PDP endpoint construction.
build-security/opa-symfony-middleware pull request #11
Opened 2021-02-24 14:23 UTC by yashtewari

Can now handle a larger variety of input from the configuration.

Example: PDP_HOSTNAME can be localhost, or http://localhost,
or http://localhost/ and so on.

2021-02-24 14:30 UTC, shahar-davidson commented on src/OpenPolicyAgent.php
> +    private function getPDPEndpoint(): string {
(1) This is kind of confusing - on the one hand we instruct the developers to define PDP_PORT PDP_POLICY_PATH PDP_HOSTNAME, etc., but on the other hand we are not really using those.
So, if we resort to this logic,  we should instruct the users to supply a single env var that will hold the full URL.
(2) If we decide that only a single env var is required (because we do the parsing) then it should probably be called PDP_URL

I personally prefer to separate all parameters in order to avoid  errors that might be encountered in the logic below.
In addition, keep in mind the we will need to align the chosen convention for parameter passing in all our MW/SDKs

2021-02-24 14:33 UTC, yashtewari commented on src/OpenPolicyAgent.php
> +    private function getPDPEndpoint(): string {
When you say "we are not really using those", you mean that we are _only_ using them to construct the final URL, right?

2021-02-24 14:50 UTC, shahar-davidson commented on src/OpenPolicyAgent.php
> +    private function getPDPEndpoint(): string {
my bad - I did not read the function correctly...

2021-02-24 14:51 UTC, shahar-davidson commented on src/OpenPolicyAgent.php
> +    private function getPDPEndpoint(): string {
So the only thing left is to add a unit test for this function

2021-02-25 06:26 UTC, shahar-davidson requested changes

2021-02-25 06:26 UTC, shahar-davidson commented on src/OpenPolicyAgent.php
> +        catch (\Exception $e) {
What's this "\" doing before `Exception`? :) 
Is that part of the syntax or is a mistake?

2021-02-25 06:30 UTC, yashtewari commented on src/OpenPolicyAgent.php
> +        catch (\Exception $e) {
The backslash? It tells PHP that we want to use `Exception` as defined in the global namespace.

2021-02-25 06:30 UTC, shahar-davidson approved these changes

2021-02-25 06:31 UTC, merged